version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    labels:
      - dependencies
    schedule:
      interval: weekly
    versioning-strategy: increase
    open-pull-requests-limit: 1

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - github-actions
